# Generated by Django 4.0.1 on 2022-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JatahCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cuti', models.CharField(max_length=50)),
                ('persyaratan', models.TextField()),
                ('jatah', models.IntegerField()),
                ('nip_pejabat', models.CharField(max_length=18)),
            ],
        ),
    ]
