# Generated by Django 4.0.1 on 2022-02-05 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JatahCuti',
            new_name='JenisCuti',
        ),
        migrations.CreateModel(
            name='FormCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pns_id', models.CharField(max_length=18)),
                ('pns_nama', models.CharField(max_length=100)),
                ('pns_unit_kerja', models.CharField(max_length=100)),
                ('pns_jabatan', models.CharField(max_length=100)),
                ('pns_masa_kerja', models.IntegerField()),
                ('alasan', models.TextField()),
                ('selama', models.IntegerField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('catatan_cuti', models.JSONField()),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=13)),
                ('atasan_nip', models.CharField(max_length=18)),
                ('persetujuan_atasan', models.CharField(choices=[('DS', 'Disetujui'), ('P', 'Perubahan'), ('DT', 'Ditangguhkan'), ('TDS', 'Tidak Disetujui')], max_length=3)),
                ('form_scan_berstempel', models.CharField(max_length=100)),
                ('nip_pejabat', models.CharField(max_length=100)),
                ('persetujuan_pejabat', models.CharField(choices=[('DS', 'Disetujui'), ('P', 'Perubahan'), ('DT', 'Ditangguhkan'), ('TDS', 'Tidak Disetujui')], max_length=3)),
                ('form_scan_bertanda_tangan', models.CharField(max_length=100)),
                ('jenis_cuti_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jeniscuti')),
                ('pengisi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilePersyaratan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('form_cuti_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formcuti')),
            ],
        ),
    ]
