# Generated by Django 4.0.1 on 2022-02-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userlevel_unitkerja_bapeg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlevel',
            old_name='Level',
            new_name='level',
        ),
    ]
