# Generated by Django 4.0.1 on 2022-02-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_level_userlevel_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitkerja',
            old_name='api_unit_kerja_id',
            new_name='api_unit_kerja',
        ),
        migrations.RemoveField(
            model_name='bapeg',
            name='unit_kerja_id',
        ),
        migrations.RemoveField(
            model_name='filepersyaratan',
            name='form_cuti_id',
        ),
        migrations.RemoveField(
            model_name='formcuti',
            name='jenis_cuti_id',
        ),
        migrations.AddField(
            model_name='bapeg',
            name='unit_kerja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempat_unit', to='api.unitkerja'),
        ),
        migrations.AddField(
            model_name='filepersyaratan',
            name='form_cuti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_syarat', to='api.formcuti'),
        ),
        migrations.AddField(
            model_name='formcuti',
            name='jenis_cuti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenis_cuti', to='api.jeniscuti'),
        ),
        migrations.AlterField(
            model_name='bapeg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anggota_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formcuti',
            name='pengisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitkerja',
            name='atasan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atasan_unit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
